### ISSUE TITLE
Instalación de la App Bizagi y realización del Modelo  de Negocios

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/actividad-6-proceso-de-negocio-en-bizagi-proyecto-equipo-yce#1]
[REPORTE DE PRÁCTICA._ 6 MODELO DE NEGOCIOS EN BIZAGI - EQUIPO YCE.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-proceso-de-negocio-en-bizagi-proyecto-equipo-yce/files/12825860/REPORTE.DE.PRACTICA._.6.MODELO.DE.NEGOCIOS.EN.BIZAGI.-.EQUIPO.YCE.pdf)

**Comment by lucero012** [comment]
20/20
Excelente trabajo, continúen así

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
